---
title: "Correspondence Analysis"
author: "David C. King"
date: "4/5/2022"
output:
  powerpoint_presentation: default

---

Various references:

The procedure and its calculation:

https://www.displayr.com/math-correspondence-analysis/

Using count data:

https://stats.stackexchange.com/questions/68938/multiple-correspondence-analysis-for-count-data-entered-as-binary-variables

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(factoextra)
library(ggplot2)
library(ade4)
library(tidyr)
library(dplyr)
library(GenomicRanges)
library(ggrepel)
#install.packages("devtools")
#devtools::install_github("meekrob/ParasiteXML") # Brings biomaRt, GenomicRanges
library(ParasiteXML)
bcd=getwd()
setwd('/Users/david/work/ELT-2-ChIP-revision/David/01_promoters/02_scripts')
source('david-reader.R')
setwd(bcd)
library(knitr)
library(kableExtra)
library(flextable)
```

```{r read-data}
setwd('/Users/david/work/ELT-2-ChIP-revision/David/01_promoters/02_scripts')
elt2.data = read_ELT2_binding_data(as_genomic_ranges = FALSE)
intestine = read_rob_all_merged() %>% dplyr::select(-starts_with("pvalue."),-starts_with("lfcSE."))
elt2.intestine = inner_join(intestine, elt2.data, by = "WBGeneID")
```

```{r query-promoters-or-read-saved}
setwd('/Users/david/work/ELT-2-ChIP-revision/David/01_promoters/02_scripts')
# Promoters
PROMOTERS_RDS_PATH = file.path("bioMart_saved_queries", "promoters.rds")

if (! file.exists(PROMOTERS_RDS_PATH)) {
  library(biomaRt)
  mart = getParamart()
  
  promoters = getCElegansPromoters(mart, upstream = UPSTREAM, downstream = DOWNSTREAM) 
  promoters = trim(sort(promoters, ignore.strand=T)) # trim because one interval is chrIV:-359-840 at -1000/+200
  
  saveRDS(promoters, PROMOTERS_RDS_PATH)
}else { 
  message("Using saved promoter query.")
  promoters = readRDS(PROMOTERS_RDS_PATH)
}

```


```{r read-all-modENCODE-binding-sites}
allBindingSites = read.table('all.modENCODE.binding.bed')
header = read.table('all.modENCODE.binding.bed', nrows = 1, comment.char = "")
header[1] <- 'chrom'
colnames(allBindingSites) <- header
allBindingSites[1:5,1:20]
gr.bindingsites = makeGRangesFromDataFrame(allBindingSites, keep.extra.columns = T)
```

```{r binding-sites-to-promoters}
olap = GenomicRanges::findOverlaps(promoters, gr.bindingsites, ignore.strand=T,minoverlap = 100)
# create blank columns 
gr.bindingsites$WBGeneID = NA
gr.bindingsites$gene_name = NA 
# fill data with match
gr.bindingsites[to(olap)]$WBGeneID = promoters[from(olap)]$wbps_gene_id
gr.bindingsites[to(olap)]$gene_name = promoters[from(olap)]$external_gene_id
gr.promoter.bindingsites = gr.bindingsites[ !is.na(gr.bindingsites$WBGeneID)]
length(gr.promoter.bindingsites)
```

### here is a header

```{r big-data}
promoter.bindingsites = mcols(gr.promoter.bindingsites)
bigDF = right_join(elt2.intestine, promoter.bindingsites, by = "WBGeneID",copy=T)
# NOTE: copy=T is required by:
# Error in `auto_copy()`:
# ! `x` and `y` must share the same src.
# ℹ set `copy` = TRUE (may be slow).
# Backtrace:
#  1. dplyr::left_join(elt2.intestine, promoter.bindingsites, by = "WBGeneID")
#  2. dplyr:::left_join.data.frame(...)
#  3. dplyr::auto_copy(x, y, copy = copy)
bigDF %<>% mutate(LE_bound = ifelse(LE_bound, 1L, 0L), # need to apply as.logical() later
                  L1_bound = ifelse(L1_bound, 1L, 0L),
                  L3_bound = ifelse(L3_bound, 1L, 0L))
bigDF.din = bigDF %>% filter(!is.na(din.status))

#bigDF.din[is.na(bigDF.din)] <- "ftr" # FTRs replace any not enriched/equal/depleted

```


### aggregation header

```{r aggregation, warning=FALSE, message=FALSE, echo=FALSE}

x = bigDF.din %>% filter(embryo_int_exp == 'enriched' & L1_int_exp == 'enriched')

# compress multi-hits (more than 1 TF in a given promoter)
x.nr = x %>% group_by(gene_name) %>% 
  select(din.status.description, ends_with("_bound"), AHA.1:ZTF.7) %>%
  summarize(din.status.description=unique(din.status.description), 
            across(LE_bound:ZTF.7,
                   .fns = function(x) {as.integer(any(x))})) 

rownames(x.nr) <- x.nr$gene_name

agg1 = stats::aggregate(x.nr %>% select(LE_bound:ZTF.7), 
                       by=list(dineen.status=x.nr$din.status.description),
                       FUN=sum)
rownames(agg1) <- agg1[[1]]
agg1 = agg1[,-1]

zeroColumns = which(colSums(agg1) == 0)
agg1 = agg1[,-zeroColumns]
write.table(agg1, "CA.tab", quote=F)

agg.ca = dudi.coa(agg1, scannf=FALSE, nf=2)
# compute the dot product between points and vectors
scores = as.matrix(agg.ca$co) %*% t(as.matrix(agg.ca$li))

selectedcols = rownames(scores)[abs(apply(scores, 1, max))> .014]
fviz_ca_biplot(agg.ca,repel=TRUE,
               col.col="brown", 
               col.row="purple", 
               arrows=c(T,F), 
               select.col = list(name=selectedcols),
               max.overlaps=70) +
ggtitle("Correspondance Analysis") #+ #ylim(c(-0.5,0.5)) +
ggsave("CO_biplot.LEL1.enrichedonly.pdf", width=15, height=20)

top.scores = unlist(agg.ca$tab[3,]) %>% sort(decreasing = T) %>% head(10)
top.genenames = names(top.scores)

agg1[,top.genenames]%>% kable(caption="Top 10 Transcription factors with highest association to UP_ELT2_MINUS")

agg1[,top.genenames]%>% kbl() %>% kable_styling()
```

### Top 10 scoring TFs

```{r flextable1, echo=FALSE}

t(data.frame(up_ELT2_minus_score=top.scores)) %>% as.data.frame()%>% 
flextable() %>% colformat_double(digits=3) %>% set_caption(caption="Top 10 scoring TFs") %>%
  autofit()
```

### Genes bound by top 8 scoring TFs

```{r flextable2, echo=FALSE}
x %>% filter(rowSums(x[,top.genenames[1:8]]) > 0  & din.status.description == "up_ELT2_minus") %>%
  select(gene_name, !!!syms(top.genenames[1:8])) %>% 
  flextable() %>% set_caption(caption="Genes bound by top 8 scoring TFs") %>%
  autofit()


```

### After flextable

Here is some shit after the flextable.

```{r}

x %>% filter(rowSums(x[,top.genenames[1:8]]) > 0  & din.status.description == "up_ELT2_minus") %>%
  select(gene_name, !!!syms(top.genenames)) 

```

## Biplotter

```{r biplotter}

biplotter = function(mx.ca, threshold=1) {
  # apply a threshold to get a smaller number of points
  score_threshold = quantile(mx.ca$tab %>% unlist(), threshold)
  max_scores = apply(mx.ca$tab, 2, max)
  arrows = mx.ca$li
  points = mx.ca$co[max_scores > threshold,]
  arrows$labels = rownames(arrows)
  points$labels = rownames(points)
  arrow_labels = arrows
  arrow_labels[]
  g = ggplot(points, aes(x=Comp1, y=Comp2)) + 
    geom_hline(yintercept = 0) + 
    geom_vline(xintercept = 0) + 
    geom_point(color="brown") + 
    geom_text_repel(aes(label=labels), size=7, color="brown", max.overlaps = 20) +
    
    geom_text_repel(inherit.aes = FALSE, 
                    data= arrows %>% mutate(Axis1=replace(Axis1,round(Axis1) ==1, .75)), 
                    aes(x=Axis1, y=Axis2,label=labels), size=7, color="purple") +
    geom_segment(inherit.aes = FALSE, data=arrows, aes(x=0, y=0, 
                                                       xend=Axis1, 
                                                       yend=Axis2), 
                 color="purple",
                 size=1,
                 arrow = arrow(length = unit(0.5, "cm"))) +
    xlab(sprintf("Dim1 (%2.0f%%)", 100*explained[1])) +
    ylab(sprintf("Dim2 (%2.0f%%)", 100*explained[2])) + 
    theme(axis.title = element_text(size=15), axis.text = element_text(size=15))
    g
}


```


## Fake data to understand the method

```{r diagram-plot}

mx = matrix(c(17,0,0, 7,0,
              0,10, 7,7,0,
              0,0,  7,7,10
              ), byrow=TRUE, nrow = 3)
dimnames(mx) = list(fake_gene_class=c("unchanged","up","down"),
                    fake_TF=c("fake1","fake2","fake3","fake4","fake5"
                    ))
#rownames(mx) <- c("unchanged","up","down")
mx
knitr::kable(mx)

mx.ca = dudi.coa(mx,scannf=FALSE, nf=2)
fviz_ca_biplot(mx.ca,repel=TRUE,col.col="brown", col.row="purple", arrows=c(T,F), max.overlaps=70) + 
  theme(text = element_text(size=100),
        axis.text = element_text(size=15),
        axis.title = element_text(size=15)) +
  ggtitle(element_blank())

explained = mx.ca$eig %>% proportions()
arrows = mx.ca$li

points = mx.ca$co
arrows$labels = rownames(arrows)
points$labels = rownames(points)
arrow_labels = arrows
arrow_labels[]
ggplot(points, aes(x=Comp1, y=Comp2)) + 
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) + 
  geom_point(color="brown") + 
  geom_text_repel(aes(label=labels), size=7, color="brown") +
  
  geom_text_repel(inherit.aes = FALSE, 
                  data= arrows %>% mutate(Axis1=replace(Axis1,round(Axis1) ==1, .75)), 
                  aes(x=Axis1, y=Axis2,label=labels), size=7, color="purple") +
  geom_segment(inherit.aes = FALSE, data=arrows, aes(x=0, y=0, 
                                                     xend=Axis1, 
                                                     yend=Axis2), 
               color="purple",
               size=1,
               arrow = arrow(length = unit(0.5, "cm"))) +
  xlab(sprintf("Dim1 (%2.0f%%)", 100*explained[1])) +
  ylab(sprintf("Dim2 (%2.0f%%)", 100*explained[2])) + 
  theme(axis.title = element_text(size=15), axis.text = element_text(size=15))
```

```{r add-noise}
library(knitr)
set.seed(3)
noise1 = mx + round(runif(length(mx),max = 5))
mx.ca = dudi.coa(noise1,scannf=FALSE, nf=2)
fviz_ca_biplot(mx.ca,repel=TRUE,col.col="brown", col.row="purple", arrows=c(T,F), max.overlaps=70) + 
  theme(title = element_text(size=5),
        text = element_text(size=100),
        axis.text = element_text(size=15),
        axis.title = element_text(size=15)) +
  ggtitle("Add noise")
kable(noise1)

noise2 = mx + round(runif(length(mx),max = 5))
mx.ca = dudi.coa(noise2,scannf=FALSE, nf=2)
fviz_ca_biplot(mx.ca,repel=TRUE,col.col="brown", col.row="purple", arrows=c(T,F), max.overlaps=70) + 
  theme(title = element_text(size=5),
        text = element_text(size=100),
        axis.text = element_text(size=15),
        axis.title = element_text(size=15)) +
  ggtitle("Add noise 2")

kable(noise2)
noise3 = mx + round(runif(length(mx),max = 5))
mx.ca = dudi.coa(noise3,scannf=FALSE, nf=2)
fviz_ca_biplot(mx.ca,repel=TRUE,col.col="brown", col.row="purple", arrows=c(T,F), max.overlaps=70) + 
  theme(title = element_text(size=5),
        text = element_text(size=100),
        axis.text = element_text(size=15),
        axis.title = element_text(size=15)) +
  ggtitle("Add noise 3")
kable(noise3)
```
```{r replicator}
replicator = function(A,B,C,tot.A=17,tot.B=10,tot.C=10) {
  N = tot.A + tot.B + tot.C
  cnts = integer(N)
  lvls = factor(c( rep('unchanged', tot.A),
            rep('up', tot.B),
            rep('down', tot.C)), levels=c("unchanged","up","down"))
  a = 1
  b = min(which(lvls == 'up'))
  c = min(which(lvls == 'down'))
  cnts[a:(a+A)] <- ifelse(A,1,0)
  cnts[b:(b+B)] <- ifelse(B,1,0)
  cnts[c:(c+C)] <- ifelse(C,1,0)
}
```

```{r add-uniform}
noise1 = mx + 50
mx.ca = dudi.coa(noise1,scannf=FALSE, nf=2)
fviz_ca_biplot(mx.ca,repel=TRUE,col.col="brown", col.row="purple", arrows=c(T,F), max.overlaps=70) + 
  theme(title = element_text(size=5),
        text = element_text(size=100),
        axis.text = element_text(size=15),
        axis.title = element_text(size=15)) +
  ggtitle("Add same to every count")
```

```{r add-random-columns}
rx = matrix(round(runif(3*5, max=17)), nrow=3)
colnames(rx) <- c("rand1","rand2","rand3","rand4","rand5")

mx.ca = dudi.coa(cbind(mx,rx[,1:5]),scannf=FALSE, nf=2)
fviz_ca_biplot(mx.ca,repel=TRUE,col.col="brown", col.row="purple", arrows=c(T,F), max.overlaps=70) + 
  theme(title = element_text(size=5),
        text = element_text(size=100),
        axis.text = element_text(size=15),
        axis.title = element_text(size=15)) +
  ggtitle("Add random/uninformative columns")
```
