---
title: "OverlapChromatinStatesAndPromoters"
author: "David C. King"
date: "2023-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(magrittr)
library(RMariaDB)
library(GenomicRanges)
```

```{r getData}
source('onishRDB/R/getEvansChromatinStatesAsGRanges.R', chdir = TRUE)
source('onishRDB/R/getPromotersAsGRanges.R', chdir = TRUE)
```
```{r fractionPromoterFunction}
fractionPromoterFunction <- function(Olaps, evansChromatinStates.gr)
{
  promoters.olap = promoters.gr[from(Olaps)]
  evansChromatinStates.olap = evansChromatinStates.gr[to(Olaps)]
  
  first.start = start(promoters.olap)
  first.end = end(promoters.olap)
  second.start = start(evansChromatinStates.olap)
  second.end = end(evansChromatinStates.olap)
  
  olapRanges = cbind(first.start,first.end,second.start,second.end)
  
  bpOverlap = apply(olapRanges, 
        1, 
        function(x) {min(x[[2]], x[[4]])- max(x[[1]], x[[3]])})
  
  stopifnot(all(bpOverlap >= 0)) # 0 overlap means continuous
  
  return(bpOverlap / width(promoters.olap));
}
```

```{r}
evansChromatinStates.grList = split(evansChromatinStates.gr, evansChromatinStates.gr$stage)
EE.Olaps = GenomicRanges::findOverlaps(promoters.gr, evansChromatinStates.grList$EE)

L3.Olaps = GenomicRanges::findOverlaps(promoters.gr, evansChromatinStates.grList$L3)

fractionPromoterOlap.EE = fractionPromoterFunction(EE.Olaps,evansChromatinStates.grList$EE)

fractionPromoterOlap.L3 = fractionPromoterFunction(L3.Olaps,evansChromatinStates.grList$L3)
```

```{r getHighestPromoterCovered EE}
promoters.olap.EE = promoters.gr[from(EE.Olaps)]
evansChromatinStates.olap.EE = evansChromatinStates.grList$EE[from(EE.Olaps)]
df = mcols(promoters.olap.EE)
df$fractionPromoterCovered = fractionPromoterOlap.EE
df = cbind(df, mcols(evansChromatinStates.olap.EE))
df = as.data.frame(df)

ranked.EE = df %>% group_by(geneName) %>% reframe(WBID, geneName, fractionPromoterCovered, accession, stage,stateID, rank = rank(-fractionPromoterCovered),id_evansChromatinStates)
```

```{r getHighestPromoterCovered L3}
promoters.olap.L3 = promoters.gr[from(L3.Olaps)]
evansChromatinStates.olap.L3 = evansChromatinStates.grList$L3[from(L3.Olaps)]
df = mcols(promoters.olap.L3)
df$fractionPromoterCovered = fractionPromoterOlap.L3
df = cbind(df, mcols(evansChromatinStates.olap.L3))
df = as.data.frame(df)

ranked.L3 = df %>% group_by(geneName) %>% reframe(WBID, geneName, fractionPromoterCovered, accession, stage, stateID, rank = rank(-fractionPromoterCovered, ties.method="first"),id_evansChromatinStates)
```

```{r CSVs for SQL load data from file, eval=FALSE}
write_csv(ranked.EE, file="OverlapChromatinStatesAndPromoters.csv")
write_csv(ranked.L3, file="OverlapChromatinStatesAndPromoters.csv", append = T)
```

```{r merge with promoter/peak overlaps}
source('OnishRDB/R/DBPeakOverlaps.R', chdir = T)
head(DBPeakOverlaps)
EE.states = ranked.EE %>% filter(rank == 1)
L3.states = ranked.L3 %>% filter(rank == 1)
nrow(EE.states)
nrow(L3.states)
EE.df = data.frame(name=EE.states$geneName, state=EE.states$stateID)
L3.df = data.frame(name=L3.states$geneName, state=L3.states$stateID)
combined = left_join(DBPeakOverlaps, EE.df, by = 'name') %>% rename(state = "state.EE")
combined = left_join(combined, L3.df, by = 'name') %>% rename(state = "state.L3")
```
